# Protectedを実現したい

<!-- more -->

# Protectedにできない問題

```javascript
class C {constructor(){this._protectedValue=0;}}
class D extends C {constructor() {super._protectedValue=1;}}
const c = new C()
const d = new D()
c._protectedValue // 参照不可にしたい！
d._protectedValue // 参照不可にしたい！
```
```javascript
class C {
    #privateValue;
    constructor(){this.#privateValue=0;}
}
class D extends C {constructor() {super.#privateValue=1;}} // 参照したいのに不可！
const c = new C()
const d = new D()
c.#privateValue // 参照不可（期待通り）
d.#privateValue // 参照不可（期待通り）
```

# Protectedにしよう案

　呼出元が定義元かその継承先であるなら参照でき、そうでないなら参照不可にすれば良い。

　`Function.caller`は自身の呼出元を返す。が、非推奨になったため使用不能。

　そこで呼び出す時に毎回、呼出元`this`を明示的に渡すことで判定する。冗長だが、これで解決できる。

```javascript
class ProtectValues {
    #context; #names;
    constructor(context) {
        this.#context = context.constructor
        this.#names = new Map()
    }
    add(name, value, context) {if (this.#validCtx(context)) {this.#names.set(name, value)}}
    set(name, value, context) {
        if (this.#validCtx(context)) {
            if (this.#names.has(name)) {this.#names.set(name, value)}
            else {throw new TypeError(`Not exist '${name}'`)}
        }
    }
    get(name, context) {
        if (this.#validCtx(context)) {return this.#names.get(name)}
    }
    #validCtx(context) {
        if (context instanceof this.#context) {return true}
        else {throw new TypeError(`Invalid context.`)}
    }
}
class C {
    constructor(){
        this._ = new ProtectValues(this)
        this._.add('id', 0, this)
        this._.set('id', 1, this)
    }
}
class D extends C {
    constructor(){
        super._.set('id', 2, this)
    }
}
const c = new C()
const d = new D()
c._.get('id', this) // TypeError: Invalid context.
d._.get('id', this) // TypeError: Invalid context.
```


